services:
  nginx:
    image: nginx:1.30.3-alpine
    container_name: nginx
    restart: unless-stopped
    mem_limit: 128m
    ports:
      - "80:80"
    networks:
      - food-del-app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    
    depends_on:
      - food-del-backend
      - food-del-frontend
      - food-del-admin
 
     
  food-del-backend:
    image: food-del-backend:latest
    container_name: food-del-backend
    restart: unless-stopped
    user: node
    mem_limit: 500m
    expose:
      - "4000"
    env_file:
      - ./env/backend.env
    networks:
      - food-del-app
    
  food-del-frontend:
    image: food-del-frontend:latest
    container_name: food-del-frontend
    restart: unless-stopped
    mem_limit: 500m
    expose:
      - "80"
    env_file:
      - ./env/frontend.env
    networks:
      - food-del-app
  
  food-del-admin:
    image: food-del-admin:latest
    container_name: food-del-admin
    restart: unless-stopped
    mem_limit: 500m
    expose:
      - "80"
    env_file:
      - ./env/admin.env
    networks:
      - food-del-app
 
networks:
  food-del-app:
    driver: bridge
